version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: alpine:3.13
    container_name: api_script_runner
    depends_on:
      - postgres
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    environment:
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
    entrypoint: ["/bin/sh", "-c", "apk add --no-cache curl postgresql-client jq && sh /app/etl.sh"]

volumes:
  postgres_data: